name: voxai
description: "VoxAI - Intelligent Voice Assistant powered by Gemini AI"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  google_generative_ai: ^0.2.1
  url_launcher: ^6.1.7
  contacts_service_plus: ^0.0.2
  geolocator: ^9.0.2
  weather: ^3.2.1
  android_intent_plus: ^4.0.0
  intl: ^0.18.0
  timezone: ^0.9.1
  permission_handler: ^11.3.0
  speech_to_text: ^7.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  # Add any assets you might need in the future
  # - assets/images/